# fly.toml app configuration file generated for gogym on 2024-05-20T23:42:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gogym'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]
  image = "registry.fly.io/gogym:latest"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 3001
  protocol = "tcp"
  auto_start_machines = true

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.concurrency]]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1m"
    restart_limit = 0


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
