default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: GoGym_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: GoGym_test
  host: db
  username: postgres
  password: password

# fly.ioデプロイ時の設定
# production:
#   <<: *default
#   database: <%= ENV["DATABASE_NAME"] %>
#   username: <%= ENV["DATABASE_USER"] %>
#   password: <%= ENV["DATABASE_PASSWORD"] %>
#   host: <%= ENV["DATABASE_HOST"] %>
#   port: <%= ENV["DATABASE_PORT"] %>
#   url: <%= ENV['DATABASE_URL'] %>
#   # Fly.ioではSSLを使用することが推奨されます
#   sslmode: require
  # <<: *default
  # database: GoGym_production
  # username: GoGym
  # password: <%= ENV["GOGYM_DATABASE_PASSWORD"] %>
